ogr2ogr -f "GeoJSON" -t_srs http://spatialreference.org/ref/epsg/4326/ district.geojson swissBOUNDARIES3D_1_1_TLM_BEZIRKSGEBIET.shp
ogr2ogr -f "GeoJSON" -t_srs http://spatialreference.org/ref/epsg/4326/ canton.geojson swissBOUNDARIES3D_1_1_TLM_KANTONSGEBIET.shp
ogr2ogr -f "GeoJSON" -select Name,BFS_NUMMER,BEZIRKSNUM,KANTONSNUM,EINWOHNERZ -t_srs http://spatialreference.org/ref/epsg/4326/ cities.geojson swissBOUNDARIES3D_1_1_TLM_HOHEITSGEBIET.shp

ogr2ogr -f "KML" -t_srs http://spatialreference.org/ref/epsg/4326/ district.kml swissBOUNDARIES3D_1_1_TLM_BEZIRKSGEBIET.shp
ogr2ogr -f "KML" -t_srs http://spatialreference.org/ref/epsg/4326/ canton.kml swissBOUNDARIES3D_1_1_TLM_KANTONSGEBIET.shp
ogr2ogr -f "KML" -simplify 25 -t_srs http://spatialreference.org/ref/epsg/4326/ cities.kml swissBOUNDARIES3D_1_1_TLM_HOHEITSGEBIET.shp
